import { defineCollection } from "astro:content";
import { file } from "astro/loaders";
import { z } from "zod";
import { directorySchema } from "@validation/directory";

// jbcom/pkgs only uses the JSON source. The file is generated by
// scripts/generate-directory.mjs on prebuild/predev from the
// Formula/, bucket/, and choco/ manifests committed to this repo.
export function createDirectoryCollection() {
  return defineCollection({
    loader: file("src/data/directory/directory.json"),
    schema: ({ image }) =>
      directorySchema(image()).extend({
        // Extensions our custom components read; optional so the base
        // template still renders if they're absent.
        packagers: z.record(z.string(), z.string()).optional(),
        license: z.string().optional(),
      }),
  });
}
