# This file was generated by GoReleaser. DO NOT EDIT.
cask "radioactive-ralph" do
  version "0.35.6"

  on_macos do
    on_intel do
      sha256 "6052a41f4784a847c5601c730d634a443203a17d5f8e4de9615ed5207b67ab69"
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v#{version}/radioactive_ralph_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf8c80c093b9856d76fca142ce8fa936c74733f60a3823f601394099ee91331b"
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v#{version}/radioactive_ralph_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c781655efb0df54f53ac750c8751d7296922dfb1b97c261f40671048e4cdda3e"
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v#{version}/radioactive_ralph_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "691027809962c0ea9d62da0a8fc75692e39370ebbf2b627e24ec0e0e346915f0"
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v#{version}/radioactive_ralph_#{version}_linux_arm64.tar.gz"
    end
  end

  name "radioactive-ralph"
  desc "Supervised-execution runtime for local AI-agent CLIs"
  homepage "https://github.com/jbcom/radioactive-ralph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "radioactive_ralph"

  # No zap stanza required

  caveats <<~EOS
    Next step — start the supervisor, then register a project:

      radioactive_ralph service install
      radioactive_ralph --init

    Run `radioactive_ralph` inside a registered project for the
    read-only TUI once the supervisor is running. Full docs:

      https://jonbogaty.com/radioactive-ralph/getting-started/
  EOS
end
