# typed: false
# frozen_string_literal: true

# This file was generated by paranoid-passwd's release pipeline.
# DO NOT EDIT.
class ParanoidPasswd < Formula
  desc "Self-auditing cryptographic password generator"
  homepage "https://github.com/jbcom/paranoid-passwd"
  version "3.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.5.2/paranoid-passwd-3.5.2-darwin-arm64.tar.gz"
      sha256 "f8bc20254a54f3a4fe8f6bd3da9861b0224d8072c240190ee7f84ea601f20e49"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.5.2/paranoid-passwd-3.5.2-darwin-amd64.tar.gz"
      sha256 "8ef778a014ada299da429e0c3415d40138b8c7cecec89836606eb398ba6f75a5"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.5.2/paranoid-passwd-3.5.2-linux-arm64.tar.gz"
      sha256 "dbc575fc87e204c5616b2405fd12430ce394f6349fad34927de0b7488b12c258"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.5.2/paranoid-passwd-3.5.2-linux-amd64.tar.gz"
      sha256 "78d5602411614d2cfc81eeb8c9472ae3424f2caefa2461457d8d8e15ffc5b876"
    end
  end

  def install
    bin.install "paranoid-passwd"
  end

  test do
    system "#{bin}/paranoid-passwd", "--version"
  end
end
