# typed: false
# frozen_string_literal: true

# This file was generated by paranoid-passwd's release pipeline.
# DO NOT EDIT.
class ParanoidPasswd < Formula
  desc "Local-first password manager and generator with CLI and TUI"
  homepage "https://github.com/jbcom/paranoid-passwd"
  version "3.6.5"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.6.5/paranoid-passwd-3.6.5-darwin-arm64.tar.gz"
      sha256 "6d31f82ef205a6a59be1003768bbcf73953c1a63406282416538ea4da017a522"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.6.5/paranoid-passwd-3.6.5-darwin-amd64.tar.gz"
      sha256 "97e18ccf54d3d7fa645e3942181bdea1de2d5911c9c63bdd9d29aaab96121498"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.6.5/paranoid-passwd-3.6.5-linux-arm64.tar.gz"
      sha256 "dca563f1c336e2613fe0f65d073e856dbf7d748a312a421f4bc192d6f84b9ea4"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/paranoid-passwd/releases/download/paranoid-passwd-v3.6.5/paranoid-passwd-3.6.5-linux-amd64.tar.gz"
      sha256 "cd232e5d4076ae67a575ce7c777abf2733abc477f7642e66894740f246d84cd9"
    end
  end

  def install
    bin.install "paranoid-passwd"
  end

  test do
    system "#{bin}/paranoid-passwd", "--version"
  end
end
