# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadioactiveRalph < Formula
  desc "Autonomous continuous development orchestrator for Claude Code"
  homepage "https://github.com/jbcom/radioactive-ralph"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.6.0/radioactive_ralph_0.6.0_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.6.0/radioactive_ralph_0.6.0_darwin_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.6.0/radioactive_ralph_0.6.0_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.6.0/radioactive_ralph_0.6.0_linux_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "radioactive_ralph"
  end

  test do
    system "#{bin}/radioactive_ralph", "--version"
  end
end
