# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadioactiveRalph < Formula
  desc "Binary-first repo runtime with many Ralph personalities"
  homepage "https://github.com/jbcom/radioactive-ralph"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.2/radioactive_ralph_0.8.2_darwin_amd64.tar.gz"
      sha256 "e03480e26b2fdb9a585f2509fb9d33e97021c5d8ca2ab8240cedf965e3551931"

      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.2/radioactive_ralph_0.8.2_darwin_arm64.tar.gz"
      sha256 "5f9f417e9b1ff3992d8841f7f6986cf0a577bba96314893e0bed96217a59ecee"

      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.2/radioactive_ralph_0.8.2_linux_amd64.tar.gz"
      sha256 "ac1f6a1ea675dd0fa13ca1ebe2af486ee070da0310f4b1fb9294ca67a719d392"
      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.2/radioactive_ralph_0.8.2_linux_arm64.tar.gz"
      sha256 "296300284022a06a9624f94cc7ccb58aaa98c653230aa3d740ee2ec8ab873685"
      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
  end

  def caveats
    <<~EOS
      Next step — initialize a repo and let Fixit seed the first plan:

        radioactive_ralph init
        radioactive_ralph run --variant fixit --advise --topic bootstrap
        radioactive_ralph service start

      Use `radioactive_ralph tui` for the cockpit once the repo service
      is running. Full docs:

        https://jonbogaty.com/radioactive-ralph/getting-started/
    EOS
  end

  test do
    system "#{bin}/radioactive_ralph", "--version"
  end
end
