# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RadioactiveRalph < Formula
  desc "Binary-first repo runtime with many Ralph personalities"
  homepage "https://github.com/jbcom/radioactive-ralph"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.1/radioactive_ralph_0.8.1_darwin_amd64.tar.gz"
      sha256 "ba400436d17777c3a69103f04f47f81f0b96b23eec5210354ae94dad041e2624"

      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.1/radioactive_ralph_0.8.1_darwin_arm64.tar.gz"
      sha256 "a61bc1d7d7f58d7d8f2e5bc7c26b367d9352527b07b6bdd1724ab823904d09f2"

      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.1/radioactive_ralph_0.8.1_linux_amd64.tar.gz"
      sha256 "c6410ccdf5c445ed4eb6edd3985ca35a7c5256e40f5e2f32124efbad6ad41c42"
      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jbcom/radioactive-ralph/releases/download/v0.8.1/radioactive_ralph_0.8.1_linux_arm64.tar.gz"
      sha256 "5e293196eb6291cf5a06f7bca49a2e9a91fb63059fde434b263b5e71e0d47686"
      define_method(:install) do
        bin.install "radioactive_ralph"
      end
    end
  end

  def caveats
    <<~EOS
      Next step — initialize a repo and let Fixit seed the first plan:

        radioactive_ralph init
        radioactive_ralph run --variant fixit --advise --topic bootstrap
        radioactive_ralph service start

      Use `radioactive_ralph tui` for the cockpit once the repo service
      is running. Full docs:

        https://jonbogaty.com/radioactive-ralph/getting-started/
    EOS
  end

  test do
    system "#{bin}/radioactive_ralph", "--version"
  end
end
